Upgrade Evernote SDK
volkhin/evernote-markdown pull request #3
Opened 2017-02-15 02:35 UTC by cmckni3

2017-07-20 20:35 UTC, cmckni3 commented
@volkhin ☝️

2017-07-21 03:00 UTC, volkhin requested changes

2017-07-21 03:00 UTC, volkhin commented on .editorconfig
> +root=true
thanks for the PR! Can you please remove this file?

2017-07-21 05:55 UTC, cmckni3 commented on .editorconfig
> +root=true
Sure. Do you not use [EditorConfig](http://editorconfig.org)?

2017-07-21 08:23 UTC, volkhin commented on .editorconfig
> +root=true
no, actually I never tried it. Will take a look, thanks:)

2017-07-21 08:23 UTC, merged